---
title: "Data Science HW#2"
author: "Sophia Miller"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading tidyverse
```{r tidyverse}
library(tidyverse)
```

# Problem 1
## Read and clean Mr. Trash Wheel sheet

```{r read_trashwheel}
library(readxl)
trashwheel_data = read_excel(
  path = "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N408",
  col_names = TRUE) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = as.integer(round(sports_balls, 0))
    )
``` 

## Read and clean precipitation data for 2017

```{r precip_2017}
precip_data_2017 = read_excel(
  path = "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2017 Precipitation",
  col_names = TRUE,
  skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017)
```

## Read and clean precipitation data for 2018

```{r precip_2018}
precip_data_2018 = read_excel(
  path = "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2018 Precipitation",
  col_names = TRUE,
  skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018)
```

## Combine precipitation datasets and convert month to a character variable

```{r combine_precip}
precip_data = 
  full_join(precip_data_2017, precip_data_2018, by = NULL) %>%
  transform(month = month.name)
```

